worker_processes 4;

error_log syslog:server=unix:/dev/log warn;
pid /var/snap/collabora/common/log/nginx.pid;
daemon off;

events {
    worker_connections  1024;
}

http {
    access_log syslog:server=unix:/dev/log;

    include /snap/collabora/current/nginx/etc/nginx/mime.types;
    client_body_temp_path /var/snap/collabora/common/nginx/client_body_temp;
    proxy_temp_path /var/snap/collabora/common/nginx/proxy_temp;
    fastcgi_temp_path /var/snap/collabora/common/nginx/fastcgi_temp;
    uwsgi_temp_path /var/snap/collabora/common/nginx/puwsgi_temp;
    scgi_temp_path /var/snap/collabora/common/nginx/scgi_temp;

    server {
        listen unix:/var/snap/collabora/common/web.socket;
        set_real_ip_from unix:;
        server_name localhost;

        root /snap/collabora/current/app/usr/share/coolwsd/browser/dist;

        include /var/snap/collabora/current/config/authelia-location.conf;

        location = / {
            return 302 /browser/dist/admin/admin.html;
        }

        # Admin Console (protected by Authelia)
        location ^~ /browser/dist/admin {
            include /var/snap/collabora/current/config/proxy.conf;
            include /var/snap/collabora/current/config/authelia-authrequest.conf;
            proxy_pass http://localhost:9980;
        }

        # Admin Console websocket (protected by Authelia)
        location ^~ /cool/adminws {
            include /var/snap/collabora/current/config/proxy.conf;
            include /var/snap/collabora/current/config/authelia-authrequest.conf;
            proxy_pass http://localhost:9980;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_read_timeout 36000s;
        }

        # static files (used by Nextcloud, no auth)
        location ^~ /browser {
            proxy_pass http://localhost:9980;
            proxy_set_header Host $http_host;
        }

        # WOPI discovery URL (used by Nextcloud, no auth)
        location ^~ /hosting/discovery {
            proxy_pass http://localhost:9980;
            proxy_set_header Host $http_host;
        }

        # Capabilities (used by Nextcloud, no auth)
        location ^~ /hosting/capabilities {
            proxy_pass http://localhost:9980;
            proxy_set_header Host $http_host;
        }

        # main websocket (used by Nextcloud, no auth)
        location ~ ^/cool/(.*)/ws$ {
            proxy_pass http://localhost:9980;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $http_host;
            proxy_read_timeout 36000s;
        }

        # download, presentation and image upload (used by Nextcloud, no auth)
        # we accept 'lool' to be backward compatible
        location ~ ^/(c|l)ool {
            proxy_pass http://localhost:9980;
            proxy_set_header Host $http_host;
        }
     }
}
